// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX40GW4-0W2C5WBdSMb6aoje8Io9z4Y0U',
    appId: '1:340459559746:web:9c1e287d3943c3315bc6db',
    messagingSenderId: '340459559746',
    projectId: 'chumi-2d075',
    authDomain: 'chumi-2d075.firebaseapp.com',
    storageBucket: 'chumi-2d075.firebasestorage.app',
    measurementId: 'G-G9Q34RWK05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmgPdC3dJFjenMfzG4boZSmzwrodubbeQ',
    appId: '1:340459559746:android:5614cebbe53a79705bc6db',
    messagingSenderId: '340459559746',
    projectId: 'chumi-2d075',
    storageBucket: 'chumi-2d075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwO48RiXQEIngJ6LnA2u9G4ztrgMUVGOQ',
    appId: '1:340459559746:ios:bc784329a63370095bc6db',
    messagingSenderId: '340459559746',
    projectId: 'chumi-2d075',
    storageBucket: 'chumi-2d075.firebasestorage.app',
    iosBundleId: 'com.example.flutterFrontend',
  );
}
